# 配置文件
# 数据库名称 mysql,postgresql
dbname: postgresql

# 是否开启dug模式打印sql true,false
isPrintSql: true

# 是否开启debug模式 true,false
isDebug: true

# server:
#   port: 1016

datasource:
  dirverName: mysql
  host: 127.0.0.1
  port: 3306
  database: ginessential
  username: root
  password: 123456
  charset: utf8

pgsqlsource:
  dirverName: postgresql
  host: sh-postgres-r1ko2h0i.sql.tencentcdb.com
  port: 24155
  database: gin_zc
  username: ZhouXin
  password: 9bTBzH9W2a:!bnc
  charset: utf8